// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqD5dhlXOHYQWv_v4JKRc1Dne1CYFR_Bg',
    appId: '1:588009626636:web:df227ba902355bf2546229',
    messagingSenderId: '588009626636',
    projectId: 'bseb-connect',
    authDomain: 'bseb-connect.firebaseapp.com',
    storageBucket: 'bseb-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7lrPRHmif_o5ft7StMU51AS8ZsU31Fs',
    appId: '1:588009626636:android:77e31870c4d88140546229',
    messagingSenderId: '588009626636',
    projectId: 'bseb-connect',
    storageBucket: 'bseb-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-l4NXpTN4CKrnllR_eBu3mmsVX0ANbs',
    appId: '1:588009626636:ios:83f1c94193027948546229',
    messagingSenderId: '588009626636',
    projectId: 'bseb-connect',
    storageBucket: 'bseb-connect.firebasestorage.app',
    iosBundleId: 'com.bsebconnect.bseb',
  );
}
